### PR TITLE
update for 18.0

### PR DESCRIPTION
**Pull request by OnGle**
requires https://github.com/turnkeylinux/common/pull/273

### CODE REVIEW

**Review by Christie018 — APPROVED** [review]
Code changes to update bagisto appliance look good to me. Furthermore, the changes have been documented within the changelog so I think it's good for testing :

**Review by Christie018 — CHANGES_REQUESTED** [review]
I just realized the overlay/etc/confconsole/services.txt in this appliance still has the webmin line. We should probably fix this.

**Comment by JedMeister** [comment]
Great catch @Christie018 You rock!

**Comment by JedMeister** [comment]
I've addressed the confconsole oversight (https://github.com/turnkeylinux-apps/bagisto/commit/efa9e5ef141e18d67ffbbe60939bf57f59182ce4) and tidied the changelog (https://github.com/turnkeylinux-apps/bagisto/commit/f3fbf3f8442075d70bf34e812c38d2fed07741ed) and merged.

**Pull request merged**
